config/routes.rb
Rails.application.routes.draw do
  root "fruits#index"
  resources :fruits, only: [:index, :show]

  get 'fruits/:id', to: 'fruits#show', as: :fruit_info
  get 'all_data', to: 'fruits#all_data'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fruit.rb
class Fruit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fruits_controller.rb
class FruitsController < ApplicationController
  before_action :client, only: [:index, :show, :all_data]

  def index
    @fruits = client.getFruits
  end

  def show
    name = params[:id]
    @fruit = client.getFruit(name)
  end

  def all_data
    res = client.getFruits
    render json: res
  end

  private

  def client
    Fruityvice::V1::Client.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fruits_helper.rb
module FruitsHelper
end

app/views/fruits/_fruit.html.erb
<div id="<%= dom_id fruit %>">
</div>

app/views/fruits/edit.html.erb
<h1>Editing fruit</h1>

<%= render "form", fruit: @fruit %>

<br>

<div>
  <%= link_to "Show this fruit", @fruit %> |
  <%= link_to "Back to fruits", fruits_path %>
</div>

app/views/fruits/index.html.erb
<section class="container">
  <div class='logo flex'>
   
    <h1>Fruityvice API Wrapper</h1>
     <%= image_tag("fruity-vice-food-api.png") %>
  </div>
  

  <% if @fruits %>  
    <ul class="fruit-list">
      <% @fruits.each_slice((@fruits.size/3.0).ceil) do |slice| %>
        <div class="column">
          <% slice.each do |fruit| %>
            <li>
              <h2 class="hover:bg-blue-400 max-w-[90%] truncate rounded-md px-2">
                <%= link_to fruit['name'], fruit_info_path(fruit['name']) %> 
              </h2>
            </li>
          <% end %>
        </div>
      <% end %>
    </ul>
  <% else %>
    <p>No fruits found!</p>
  <% end %>

  <div class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">
  <%= link_to "View data", all_data_path %>
  </div>
</section>

app/views/fruits/new.html.erb
<h1>New fruit</h1>

<%= render "form", fruit: @fruit %>

<br>

<div>
  <%= link_to "Back to fruits", fruits_path %>
</div>

app/views/fruits/show.html.erb
<% if @fruit %>
  <h1><%= @fruit['name'] %></h1><br>
  <ul>
    <li>Family: <%= @fruit['family'] %></li>
    <li>Order: <%= @fruit['order'] %></li>
    <li>Genus: <%= @fruit['genus'] %></li>
  </ul>
 
 <h6 class="text-lg font-bold text-left">Nutrients:</h6>
  <ul>
    <li>Calories: <%= @fruit['nutritions']['calories'] %></li>
    <li>Sugar: <%= @fruit['nutritions']['sugar'] %></li>
    <li>Fat: <%= @fruit['nutritions']['fat'] %></li>
    <li>Carbohydrates: <%= @fruit['nutritions']['carbohydrates'] %></li>
    <li>Protein: <%= @fruit['nutritions']['protein'] %></li>
  </ul>

<% else %>
  <p>Fruit not found!</p>
<% end %>

<div class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">
  <%= link_to "Back to fruits", fruits_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fruityvice API Wrapper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>